### DISCUSSION TITLE
Should we add a `do not merge` label that prevents merging?

### DISCUSSION THREAD

**Discussion by Snailedlt** [devicons/devicon#1429] [Ideas]
Would it be useful to have a `do not merge` label?
Maybe the PR could have a job that fails if the label is applied too.

Example implementation from here: <https://www.jessesquires.com/blog/2021/08/24/useful-label-based-github-actions-workflows/#updated-21-march-2022>
```yaml
name: Do Not Merge

on:
  pull_request:
    types: [synchronize, opened, reopened, labeled, unlabeled]

jobs:
  do-not-merge:
    if: ${{ contains(github.event.*.labels.*.name, 'do not merge') }}
    name: Prevent Merging
    runs-on: ubuntu-latest
    steps:
      - name: Check for label
        run: |
          echo "Pull request is labeled as 'do not merge'"
          echo "This workflow fails so that the pull request cannot be merged"
          exit 1
```
