### DISCUSSION TITLE
Is there a way to configure font display?

### DISCUSSION THREAD

**Discussion by rimzzlabs** [devicons/devicon#2424] [Q&A]
How can I possible change the way font display on the browser?

currently the display of the font family is **block**, and I want to make it to be **swap** because it blocks First Contentful Paint on my site

<img width="344" alt="image" src="https://github.com/user-attachments/assets/eb81f8a1-6be5-424a-b07b-e980e1ba98f8" />

**Comment by Snailedlt** [comment]
Have you tried adding this css?

```css
@font-face {
    font-display: swap !important;
}
```

**Reply by rimzzlabs** [reply]
```css

@font-face {
	font-family: "devicon";
	display: swap;
}
```

I did, and it doesn't seems to work I think? cause the score I got from Lighthouse still warn me about render blocking font display
